#!/usr/bin/env bash
# SessionStart Hook: Worktree port namespace
# Pattern: MindStudio/Augment 2026 — collision-free dev servers across parallel worktrees
#
# Detects current git worktree position and computes namespaced ports:
#   PORT_BASE = 3000 + WORKTREE_INDEX*10
#   DB_PORT   = 5400 + WORKTREE_INDEX*10
#   WEB_PORT  = PORT_BASE
#
# Injects values as additionalContext on session start so spawned dev servers
# and the agent itself can read deterministic ports without manual config.
#
# No-op silently when not in a worktree.
#
# Input:  Claude Code SessionStart hook JSON via stdin (may be empty)
# Output: JSON {"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"..."}}
#         (additionalContext MUST be nested under hookSpecificOutput or the harness drops it)

set -euo pipefail

# Resolve repo root from the hook script location (do not trust cwd)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

emit_noop() {
    # Emit minimal JSON (no additionalContext) so Claude Code accepts the hook
    printf '{"hookEventName":"SessionStart"}\n'
    exit 0
}

# Drain stdin so callers don't block (we don't need it)
if [ ! -t 0 ]; then
    cat >/dev/null 2>&1 || true
fi

# Require git + a worktree environment
command -v git >/dev/null 2>&1 || emit_noop

cd "$REPO_ROOT" 2>/dev/null || emit_noop

# git worktree list --porcelain emits blocks separated by blank lines, each
# starting with `worktree <path>`. The main worktree is first (index 0).
worktree_list=$(git worktree list --porcelain 2>/dev/null) || emit_noop
[ -n "$worktree_list" ] || emit_noop

# Build array of worktree paths (bash 3.x compatible — no mapfile)
WT_PATHS=()
while IFS= read -r p; do
    [ -n "$p" ] && WT_PATHS+=("$p")
done < <(printf '%s\n' "$worktree_list" | awk '/^worktree /{print $2}')
[ "${#WT_PATHS[@]}" -gt 0 ] || emit_noop

# Identify current worktree by its top-level path
current_top=$(git rev-parse --show-toplevel 2>/dev/null) || emit_noop

WORKTREE_INDEX=-1
for i in "${!WT_PATHS[@]}"; do
    if [ "${WT_PATHS[$i]}" = "$current_top" ]; then
        WORKTREE_INDEX=$i
        break
    fi
done

# If we couldn't locate ourselves, no-op
[ "$WORKTREE_INDEX" -ge 0 ] || emit_noop

# Compute namespaced ports
PORT_BASE=$((3000 + WORKTREE_INDEX * 10))
DB_PORT=$((5400 + WORKTREE_INDEX * 10))
WEB_PORT=$PORT_BASE
API_PORT=$((PORT_BASE + 1))

worktree_name=$(basename "$current_top")
total_worktrees=${#WT_PATHS[@]}

# Persist to a sidecar env file so child processes (dev servers spawned later)
# can source it. Idempotent — overwrite each session.
ENV_FILE="$REPO_ROOT/.loom-worktree-env"
{
    printf '# Generated by worktree-port-namespace.sh — do not edit by hand\n'
    printf 'export WORKTREE_INDEX=%s\n' "$WORKTREE_INDEX"
    printf 'export PORT_BASE=%s\n' "$PORT_BASE"
    printf 'export DB_PORT=%s\n' "$DB_PORT"
    printf 'export WEB_PORT=%s\n' "$WEB_PORT"
    printf 'export API_PORT=%s\n' "$API_PORT"
} > "$ENV_FILE" 2>/dev/null || true

# Compose additionalContext for the agent
context=$(cat <<CTX
**WORKTREE PORT NAMESPACE** (auto-detected):
- Worktree: ${worktree_name} (index ${WORKTREE_INDEX} of ${total_worktrees})
- PORT_BASE=${PORT_BASE}  WEB_PORT=${WEB_PORT}  API_PORT=${API_PORT}  DB_PORT=${DB_PORT}
- Persisted to .loom-worktree-env (source it before launching dev servers)
- Use these ports to avoid collisions with sibling worktrees.
CTX
)

# JSON-escape the context (newlines + quotes only — bash strings are safe otherwise)
escaped=${context//\\/\\\\}
escaped=${escaped//\"/\\\"}
escaped=${escaped//$'\n'/\\n}

printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\n' "$escaped"
exit 0
