#!/usr/bin/env bash
# Contract Tests: Plugin Command Bridge
# Validates dynamic bridge between plugins/*/commands/ → .claude/commands/
set -euo pipefail

PASS=0; FAIL=0; TOTAL=0

assert() {
  TOTAL=$((TOTAL + 1))
  local desc="$1"; local condition="$2"
  if eval "$condition"; then
    echo "  ✅ PASS: $desc"; PASS=$((PASS + 1))
  else
    echo "  ❌ FAIL: $desc"; FAIL=$((FAIL + 1))
  fi
}

BRIDGE_MARKER="AUTO-GENERATED by plugin-bridge"

echo "═══ Plugin Command Bridge Tests ═══"
echo ""

# ── Bridge Script Tests ──
echo "Bridge script infrastructure"
assert "sync-plugin-commands.sh exists" "[ -f .specify/scripts/bash/sync-plugin-commands.sh ]"
assert "sync-plugin-commands.sh is executable" "[ -x .specify/scripts/bash/sync-plugin-commands.sh ]"

# Run the bridge sync
echo ""
echo "Running bridge sync..."
SYNC_OUTPUT=$(.specify/scripts/bash/sync-plugin-commands.sh sync 2>&1) || true
echo "$SYNC_OUTPUT" | head -20

# ── Manifest Tests ──
echo ""
echo "Bridge manifest"
assert "Manifest exists" "[ -f .claude/commands/.bridge-manifest.json ]"
assert "Manifest is valid JSON" "python3 -c 'import json; json.load(open(\".claude/commands/.bridge-manifest.json\"))'"
assert "Manifest has bridged section" "python3 -c 'import json; d=json.load(open(\".claude/commands/.bridge-manifest.json\")); assert \"bridged\" in d'"
assert "Manifest has static section" "python3 -c 'import json; d=json.load(open(\".claude/commands/.bridge-manifest.json\")); assert \"static\" in d'"
assert "Manifest has generated timestamp" "python3 -c 'import json; d=json.load(open(\".claude/commands/.bridge-manifest.json\")); assert \"generated\" in d'"

# ── Command Coverage Tests ──
echo ""
echo "Plugin command coverage"

# Count plugin commands (excluding template)
PLUGIN_CMD_COUNT=0
BRIDGE_CMD_COUNT=0
MISSING_CMDS=""

for plugin_dir in plugins/*/; do
  plugin_name=$(basename "$plugin_dir")
  [ "$plugin_name" = "sdd-domain-template" ] && continue
  [ -d "${plugin_dir}commands" ] || continue
  
  for cmd_file in "${plugin_dir}commands/"*.md; do
    [ -f "$cmd_file" ] || continue
    cmd_name=$(basename "$cmd_file" .md)
    PLUGIN_CMD_COUNT=$((PLUGIN_CMD_COUNT + 1))
    
    # Check .claude/commands/ has this command
    if [ -f ".claude/commands/${cmd_name}.md" ]; then
      BRIDGE_CMD_COUNT=$((BRIDGE_CMD_COUNT + 1))
    else
      MISSING_CMDS="${MISSING_CMDS} ${cmd_name}"
    fi
  done
done

assert "All plugin commands have .claude/commands/ counterparts (${BRIDGE_CMD_COUNT}/${PLUGIN_CMD_COUNT})" \
  "[ $BRIDGE_CMD_COUNT -eq $PLUGIN_CMD_COUNT ]"

if [ -n "$MISSING_CMDS" ]; then
  echo "  Missing:${MISSING_CMDS}"
fi

# ── Bridge-Generated Command Quality ──
echo ""
echo "Bridge-generated command quality"

BRIDGE_VALID=0
BRIDGE_TOTAL=0
for cmd_file in .claude/commands/*.md; do
  [ -f "$cmd_file" ] || continue
  # Only check bridge-generated commands
  if head -10 "$cmd_file" | grep -q "$BRIDGE_MARKER"; then
    BRIDGE_TOTAL=$((BRIDGE_TOTAL + 1))
    
    cmd_name=$(basename "$cmd_file" .md)
    
    # Check has YAML frontmatter
    has_frontmatter=false
    if head -1 "$cmd_file" | grep -q "^---$"; then
      has_frontmatter=true
    fi
    
    # Check has name field
    has_name=false
    if head -10 "$cmd_file" | grep -q "^name:"; then
      has_name=true
    fi
    
    # Check references plugin source
    has_source=false
    if grep -q "plugins/" "$cmd_file"; then
      has_source=true
    fi
    
    if $has_frontmatter && $has_name && $has_source; then
      BRIDGE_VALID=$((BRIDGE_VALID + 1))
    else
      echo "  ⚠️  Invalid bridge command: $cmd_file (frontmatter=$has_frontmatter name=$has_name source=$has_source)"
    fi
  fi
done

assert "Bridge commands have valid format (${BRIDGE_VALID}/${BRIDGE_TOTAL})" \
  "[ $BRIDGE_VALID -eq $BRIDGE_TOTAL ]"
assert "At least 8 bridge-generated commands exist" "[ $BRIDGE_TOTAL -ge 8 ]"

# ── Static Command Protection ──
echo ""
echo "Static command protection"

# These commands existed before the bridge and should NOT be bridge-generated
STATIC_PROTECTED=0
STATIC_TOTAL=0
for static_cmd in specification debug git-push specify plan tasks create-agent create-prd create-skill initialize-project update-framework; do
  if [ -f ".claude/commands/${static_cmd}.md" ]; then
    STATIC_TOTAL=$((STATIC_TOTAL + 1))
    if ! head -10 ".claude/commands/${static_cmd}.md" | grep -q "$BRIDGE_MARKER"; then
      STATIC_PROTECTED=$((STATIC_PROTECTED + 1))
    else
      echo "  ⚠️  Static command overwritten by bridge: ${static_cmd}"
    fi
  fi
done

assert "Static commands not overwritten by bridge (${STATIC_PROTECTED}/${STATIC_TOTAL})" \
  "[ $STATIC_PROTECTED -eq $STATIC_TOTAL ]"

# ── No Orphaned Bridge Commands ──
echo ""
echo "Orphan detection"

ORPHAN_COUNT=0
for cmd_file in .claude/commands/*.md; do
  [ -f "$cmd_file" ] || continue
  if head -10 "$cmd_file" | grep -q "$BRIDGE_MARKER"; then
    cmd_name=$(basename "$cmd_file" .md)
    # Check that at least one plugin still has this command
    found=false
    for plugin_dir in plugins/*/; do
      if [ -f "${plugin_dir}commands/${cmd_name}.md" ]; then
        found=true
        break
      fi
    done
    if ! $found; then
      ORPHAN_COUNT=$((ORPHAN_COUNT + 1))
      echo "  ⚠️  Orphaned bridge command: ${cmd_name}"
    fi
  fi
done

assert "No orphaned bridge commands" "[ $ORPHAN_COUNT -eq 0 ]"

# ── Template Plugin Excluded ──
echo ""
echo "Template exclusion"
TEMPLATE_BRIDGED=0
if [ -d "plugins/sdd-domain-template/commands" ]; then
  for cmd_file in plugins/sdd-domain-template/commands/*.md; do
    [ -f "$cmd_file" ] || continue
    cmd_name=$(basename "$cmd_file" .md)
    if [ -f ".claude/commands/${cmd_name}.md" ] && head -10 ".claude/commands/${cmd_name}.md" | grep -q "$BRIDGE_MARKER"; then
      if grep -q "sdd-domain-template" ".claude/commands/${cmd_name}.md"; then
        TEMPLATE_BRIDGED=$((TEMPLATE_BRIDGED + 1))
        echo "  ⚠️  Template command bridged: ${cmd_name}"
      fi
    fi
  done
fi
assert "Template plugin commands not bridged" "[ $TEMPLATE_BRIDGED -eq 0 ]"

# ── Specific Commands Exist ──
echo ""
echo "Critical commands accessible"
assert "/research command exists" "[ -f .claude/commands/research.md ]"
assert "/create-plugin command exists" "[ -f .claude/commands/create-plugin.md ]"
assert "/finalize command exists" "[ -f .claude/commands/finalize.md ]"
assert "/swarm command exists" "[ -f .claude/commands/swarm.md ]"
assert "/build-team command exists" "[ -f .claude/commands/build-team.md ]"
assert "/fullstack-team command exists" "[ -f .claude/commands/fullstack-team.md ]"
assert "/research-team command exists" "[ -f .claude/commands/research-team.md ]"
assert "/review-team command exists" "[ -f .claude/commands/review-team.md ]"

echo ""
echo "═══════════════════════════════════════"
echo " Results: ${PASS}/${TOTAL} passed, ${FAIL} failed"
echo "═══════════════════════════════════════"
[ $FAIL -eq 0 ] && exit 0 || exit 1
