#!/usr/bin/env bash
# Contract Tests: Legacy Cleanup Validation (Post Plugin-First v4.0)
# Validates that ALL monolithic legacy artifacts have been removed
# and all capabilities are served exclusively through plugins.
set -euo pipefail

PASS=0; FAIL=0; TOTAL=0
BRIDGE_MARKER="AUTO-GENERATED by plugin-bridge"

assert() {
  TOTAL=$((TOTAL + 1))
  local desc="$1"; local condition="$2"
  if eval "$condition"; then
    echo "  ✅ PASS: $desc"; PASS=$((PASS + 1))
  else
    echo "  ❌ FAIL: $desc"; FAIL=$((FAIL + 1))
  fi
}

echo "═══ Legacy Cleanup Validation Tests ═══"
echo ""

# ── Monolithic skills removed ──
echo "Monolithic skills removed"
assert "No .claude/skills/ directory exists" "[ ! -d .claude/skills ]"

# ── Monolithic agents removed ──
echo ""
echo "Monolithic agents removed"
assert "No .claude/agents/ directory exists" "[ ! -d .claude/agents ]"

# ── Legacy indexes removed ──
echo ""
echo "Legacy indexes removed"
assert "No .claude/skill-index.json" "[ ! -f .claude/skill-index.json ]"
assert "No .claude/agent-index.json" "[ ! -f .claude/agent-index.json ]"

# ── Old constitution versions removed ──
echo ""
echo "Old constitution archives removed"
assert "No constitution-v1.6.0-archive.md" "[ ! -f .specify/memory/constitution-v1.6.0-archive.md ]"
assert "No constitution-v2.0.0-draft.md" "[ ! -f .specify/memory/constitution-v2.0.0-draft.md ]"

# ── All commands are bridge-generated (no deprecated statics) ──
echo ""
echo "All commands served via plugin bridge"
STATIC_COUNT=0
BRIDGE_COUNT=0
for cmd_file in .claude/commands/*.md; do
  [ -f "$cmd_file" ] || continue
  if head -10 "$cmd_file" | grep -q "$BRIDGE_MARKER"; then
    BRIDGE_COUNT=$((BRIDGE_COUNT + 1))
  else
    STATIC_COUNT=$((STATIC_COUNT + 1))
    echo "  ⚠️  Non-bridge command: $(basename "$cmd_file")"
  fi
done
assert "No static commands remain (found ${STATIC_COUNT})" "[ $STATIC_COUNT -eq 0 ]"
assert "All 19 commands are bridge-generated (found ${BRIDGE_COUNT})" "[ $BRIDGE_COUNT -ge 19 ]"

# ── Plugins are authoritative ──
echo ""
echo "Plugin-First completeness (v4.0)"
assert "framework-updater has plugin home" "[ -f plugins/sdd-maintenance/skills/framework-updater/SKILL.md ]"
assert "mcp-server-setup has plugin home" "[ -f plugins/sdd-maintenance/skills/mcp-server-setup/SKILL.md ]"
assert "project-initialization has plugin home" "[ -f plugins/sdd-maintenance/skills/project-initialization/SKILL.md ]"
assert "create-plugin command exists" "[ -f plugins/sdd-creation/commands/create-plugin.md ]"
assert "create-plugin skill exists" "[ -f plugins/sdd-creation/skills/create-plugin/SKILL.md ]"
assert "sdd-maintenance plugin manifest exists" "[ -f plugins/sdd-maintenance/.claude-plugin/plugin.json ]"

echo ""
echo "Plugin Command Bridge (v4.1)"
assert "Bridge script exists" "[ -x .specify/scripts/bash/sync-plugin-commands.sh ]"
assert "Bridge manifest exists" "[ -f .claude/commands/.bridge-manifest.json ]"
assert "Bridge manifest is valid JSON" "python3 -c 'import json; json.load(open(\".claude/commands/.bridge-manifest.json\"))'"
assert "Bridge manifest has no statics" "python3 -c 'import json,sys; d=json.load(open(\".claude/commands/.bridge-manifest.json\")); sys.exit(0 if len(d.get(\"static\",[])) == 0 else 1)'"

echo ""
echo "Backup files cleaned"
assert "No .bak files in .claude/" "[ \$(find .claude -name '*.bak' 2>/dev/null | wc -l | tr -d ' ') -eq 0 ]"
assert "No .backup files in root" "[ \$(find . -maxdepth 1 -name '*backup*' 2>/dev/null | wc -l | tr -d ' ') -eq 0 ]"

echo ""
echo "═══════════════════════════════════════"
echo " Results: ${PASS}/${TOTAL} passed, ${FAIL} failed"
echo "═══════════════════════════════════════"
[ $FAIL -eq 0 ] && exit 0 || exit 1
