#!/usr/bin/env bash
# Contract Tests: every git-tracked GENERATED artifact is DECLARED
#
# Closes the class behind the v6.4.0 promote leak: `.logic-loom/graph/
# graph-bridge.jsonl` — a GENERATED index of this whole repo, git-tracked, added
# after the previous release — carried the maintainer's private domain into the
# public template. The strip tooling had no way to know a new generated file
# class had appeared; only the release-time audit caught it.
#
# The invariant: a generated artifact that is git-tracked must be a DECIDED
# artifact. Either
#   (a) it is listed in .logic-loom/scripts/bash/template-strip-manifest.txt
#       (stripped / stubbed out of the public snapshot), or
#   (b) it is on the explicit ALLOW-TO-SHIP list below, each entry carrying an
#       inline reason.
# Anything in neither list fails, naming the file.
#
# ── What counts as "generated" ────────────────────────────────────────────────
# Marker-based, plus a short explicit path list. A file is GENERATED when:
#
#   (A) its HEADER REGION (first 10 lines) carries a self-declaring generation
#       BANNER in one of the exact forms this repo's generators actually emit:
#         1. an HTML comment containing "AUTO-GENERATED by plugin-bridge"
#            (sync-plugin-commands.sh wrappers in .claude/commands/)
#         2. an HTML comment opening with "<!-- Auto-generated from"
#            (the .claude/context/ module headers)
#         3. the JSON member "bridge_marker": "AUTO-GENERATED by plugin-bridge"
#            (.claude/commands/.bridge-manifest.json)
#   OR
#   (B) its path is under a KNOWN_GENERATED prefix listed below — for formats
#       with no comment syntax to carry a banner (JSONL).
#
# Why this rule and not something cleverer:
#   * The BANNER FORM matters, not the bare phrase. sync-plugin-commands.sh
#     (the generator) and tests/contract/test_deprecation.sh (which greps for
#     the marker) both contain the literal string "AUTO-GENERATED by
#     plugin-bridge" — in a shell comment and a shell assignment. Requiring the
#     emitted comment/JSON-member form keeps a file that merely MENTIONS the
#     marker from being mistaken for one that DECLARES itself generated.
#   * HEADER REGION, not whole file, for the same reason: history-scrub-rules.json
#     quotes "<!-- Auto-generated from CLAUDE.md ..." as rule data ~line 528.
#   * "Any file some script writes to" was considered and REJECTED as the rule:
#     inferring output paths out of shell (variables, heredocs, `>` in strings)
#     is guesswork, and a rule nobody can predict is a rule that gets disabled.
#     A generator that emits a banner declares its own artifacts; a format that
#     cannot carry one gets one line in KNOWN_GENERATED.
#
# Adding a new generated file class: give the generator a banner (preferred) or
# add its path prefix to KNOWN_GENERATED — then decide strip vs. ship.
#
# bash 3.2 safe: no associative arrays, no mapfile, no ${var,,}.
# Overridable for meta-testing: LOOM_STRIP_MANIFEST.
set -uo pipefail

PASS=0; FAIL=0; TOTAL=0
assert() {
  TOTAL=$((TOTAL + 1)); local desc="$1"; local condition="$2"
  if eval "$condition"; then echo "  ✅ PASS: $desc"; PASS=$((PASS + 1))
  else echo "  ❌ FAIL: $desc"; FAIL=$((FAIL + 1)); fi
}

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null)"; then :; else
  ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
fi
cd "$ROOT"

MANIFEST="${LOOM_STRIP_MANIFEST:-$ROOT/.logic-loom/scripts/bash/template-strip-manifest.txt}"

# ── Generated-artifact paths with no in-band banner ──────────────────────────
# One prefix per line. Keep this SHORT — a banner in the generator is better.
#   .logic-loom/graph/ — build-graph-bridge.sh (/graph build, /finalize) writes
#     graph-bridge.jsonl + sibling exports. JSONL has no comment syntax, so the
#     artifact cannot carry a banner. THIS is the class that leaked in v6.4.0.
KNOWN_GENERATED=".logic-loom/graph/"

# ── ALLOW-TO-SHIP ────────────────────────────────────────────────────────────
# Generated artifacts that legitimately ship in the public template. A path or a
# directory prefix (trailing '/'). Every entry needs a reason. Checked only
# AFTER the strip manifest, so a manifest entry always wins (e.g.
# .claude/commands/promote.md is stripped and never reaches this list).
#
#   .claude/commands/ — the plugin→command bridge wrappers plus
#     .bridge-manifest.json. Claude Code discovers slash commands ONLY from
#     .claude/commands/, so the harness is non-functional in a fresh clone
#     without them; they are regenerated by sync-plugin-commands.sh. Content is
#     repo-agnostic (plugin-relative source paths only) and three suites assert
#     the manifest is present (test_deprecation, test_plugin_command_bridge,
#     test_spec006_integration).
#   .claude/context/ — the modular context loaders (core/governance/agents/
#     skills/workflows.md) regenerated from CLAUDE.md + AGENTS.md by
#     load-context.sh. Documented as shipping: history-scrub-rules.json carries
#     scrub rules for all five, i.e. they are expected in the snapshot.
ALLOW_TO_SHIP=".claude/commands/
.claude/context/"

# path_matches <file> <entry> — exact, directory-prefix, or glob.
path_matches() {
  local f="$1" e="$2"
  [ -z "$e" ] && return 1
  [ "$f" = "$e" ] && return 0
  case "$e" in */) case "$f" in "$e"*) return 0 ;; esac ;;
                *) case "$f" in "$e"/*) return 0 ;; esac ;;
  esac
  case "$f" in $e) return 0 ;; esac
  return 1
}

matches_list() {
  local f="$1" list="$2" e
  while IFS= read -r e; do
    e="$(printf '%s' "$e" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
    [ -n "$e" ] || continue
    path_matches "$f" "$e" && return 0
  done <<EOF
$list
EOF
  return 1
}

# Manifest entries: drop comments, drop the `stub:` / `warn:` op prefixes (all
# three forms are deliberate, reviewed declarations), trim.
manifest_entries() {
  sed 's/[[:space:]]*#.*$//' "$MANIFEST" \
    | sed -E 's/^[[:space:]]*(stub|warn):[[:space:]]*//' \
    | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' \
    | grep -v '^$'
}

# is_generated <file>
is_generated() {
  local f="$1"
  matches_list "$f" "$KNOWN_GENERATED" && return 0
  [ -f "$f" ] || return 1
  head -10 "$f" 2>/dev/null | grep -aqE \
    -e '<!--.*AUTO-GENERATED by plugin-bridge' \
    -e '<!--[[:space:]]*Auto-generated from' \
    -e '"bridge_marker"[[:space:]]*:[[:space:]]*"AUTO-GENERATED by plugin-bridge"' \
    && return 0
  return 1
}

echo "═══ Generated Artifacts Are Declared ═══"
echo ""

echo "0. Inputs present"
assert "strip manifest present: ${MANIFEST#$ROOT/}" "[ -f \"\$MANIFEST\" ]"
if [ ! -f "$MANIFEST" ]; then
  echo ""
  echo "════════════════════════════════"
  echo " Results: $PASS/$TOTAL passed, $FAIL failed"
  echo "❌ SOME TESTS FAILED"
  exit 1
fi
MANIFEST_ENTRIES="$(manifest_entries)"
assert "strip manifest has entries" "[ -n \"\$MANIFEST_ENTRIES\" ]"

TRACKED="$(git ls-files 2>/dev/null)"
assert "git-tracked file list is readable" "[ -n \"\$TRACKED\" ]"

# ── 1. Classify tracked files ────────────────────────────────────────────────
echo ""
echo "1. Every tracked generated artifact is stripped or explicitly shippable"
GENERATED_COUNT=0
STRIPPED=""
SHIPPED=""
UNDECLARED=""
while IFS= read -r f; do
  [ -n "$f" ] || continue
  is_generated "$f" || continue
  GENERATED_COUNT=$((GENERATED_COUNT + 1))
  if matches_list "$f" "$MANIFEST_ENTRIES"; then
    STRIPPED="${STRIPPED}${f}"$'\n'
  elif matches_list "$f" "$ALLOW_TO_SHIP"; then
    SHIPPED="${SHIPPED}${f}"$'\n'
  else
    UNDECLARED="${UNDECLARED}${f}"$'\n'
  fi
done <<EOF
$TRACKED
EOF

echo "     (found $GENERATED_COUNT tracked generated artifacts)"
if [ -n "$STRIPPED" ]; then
  echo "     stripped by the template manifest:"
  printf '%s' "$STRIPPED" | sed 's/^/       - /'
fi
if [ -n "$SHIPPED" ]; then
  echo "     declared shippable (see ALLOW_TO_SHIP in this file):"
  printf '%s' "$SHIPPED" | sed 's/^/       - /'
fi
if [ -n "$UNDECLARED" ]; then
  echo "     UNDECLARED GENERATED ARTIFACT(S):"
  printf '%s' "$UNDECLARED" | sed 's/^/       - /'
  echo "     A generated artifact is tracked but nobody decided what happens to"
  echo "     it at release. Do ONE of:"
  echo "       * add it to .logic-loom/scripts/bash/template-strip-manifest.txt"
  echo "         (it is derived from THIS repo and must not ship), or"
  echo "       * add it to ALLOW_TO_SHIP in tests/contract/$(basename "${BASH_SOURCE[0]}")"
  echo "         with an inline reason saying why shipping it is safe."
fi
assert "no undeclared tracked generated artifact" "[ -z \"\$UNDECLARED\" ]"

# ── 2. The generated set is not silently empty ───────────────────────────────
# If the marker patterns ever stop matching (banner reworded, generator changed)
# this suite would pass vacuously. Anchor it: the bridge wrappers are a stable,
# always-present generated class.
echo ""
echo "2. Detection is live (guards against a vacuous pass)"
assert "at least 5 generated artifacts detected" "[ \$GENERATED_COUNT -ge 5 ]"
assert "the plugin-bridge wrappers are detected as generated" \
  "printf '%s' \"\$SHIPPED\" | grep -q '^\.claude/commands/swarm\.md$'"

# ── 3. Allow-to-ship entries are still live ──────────────────────────────────
# A stale allow entry is a silent hole: it keeps allowing a class that no longer
# exists, and the next thing dropped at that path inherits the exemption.
echo ""
echo "3. Every ALLOW_TO_SHIP entry still covers a real generated artifact"
STALE=""
while IFS= read -r e; do
  e="$(printf '%s' "$e" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//')"
  [ -n "$e" ] || continue
  hit=0
  while IFS= read -r s; do
    [ -n "$s" ] || continue
    path_matches "$s" "$e" && { hit=1; break; }
  done <<EOF2
$SHIPPED
EOF2
  [ $hit -eq 1 ] || STALE="${STALE}${e}"$'\n'
done <<EOF3
$ALLOW_TO_SHIP
EOF3
[ -n "$STALE" ] && { echo "     STALE ALLOW_TO_SHIP ENTRIES (nothing generated matches — remove them):";
  printf '%s' "$STALE" | sed 's/^/       - /'; }
assert "no stale ALLOW_TO_SHIP entry" "[ -z \"\$STALE\" ]"

echo ""
echo "════════════════════════════════"
echo " Results: $PASS/$TOTAL passed, $FAIL failed"
[ $FAIL -eq 0 ] && echo "✅ ALL TESTS PASSED" || echo "❌ SOME TESTS FAILED"
[ $FAIL -eq 0 ] && exit 0 || exit 1
