#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════════
# sync-plugin-commands.sh — Dynamic Plugin Command Bridge
# ═══════════════════════════════════════════════════════════════════
#
# Syncs plugin commands (plugins/*/commands/*.md) to .claude/commands/
# via lightweight wrapper files that point Claude to the plugin source.
#
# Key behaviors:
#   - Bridge-generated wrappers contain "AUTO-GENERATED by plugin-bridge"
#   - Static (pre-existing) commands are NEVER overwritten
#   - Template plugin (sdd-domain-template) is always excluded
#   - Manifest tracks what's bridged vs static
#   - Plugin content changes reflect automatically (wrapper just points)
#
# Usage:
#   sync-plugin-commands.sh sync     # Full sync (add + prune)
#   sync-plugin-commands.sh add      # Add missing commands only
#   sync-plugin-commands.sh prune    # Remove orphaned bridge commands
#   sync-plugin-commands.sh list     # Show command → plugin mapping
#   sync-plugin-commands.sh status   # Show static vs bridged breakdown
#
# Integration:
#   - setup.sh → calls after initial setup
#   - marketplace-install → calls after plugin install
#   - marketplace-update → calls after plugin update
# ═══════════════════════════════════════════════════════════════════
set -euo pipefail

# ── Configuration ──
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASE_DIR="$(cd "${SCRIPT_DIR}/../../.." && pwd)"
PLUGINS_DIR="${BASE_DIR}/plugins"
COMMANDS_DIR="${BASE_DIR}/.claude/commands"
MANIFEST="${COMMANDS_DIR}/.bridge-manifest.json"
BRIDGE_MARKER="AUTO-GENERATED by plugin-bridge"
TEMPLATE_PLUGIN="sdd-domain-template"

ACTION="${1:-sync}"

# ── Colors ──
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
RED='\033[0;31m'
NC='\033[0m'

# ── Helpers ──

# Check if a command file was generated by this bridge
is_bridge_command() {
  local file="$1"
  [ -f "$file" ] && head -10 "$file" 2>/dev/null | grep -q "$BRIDGE_MARKER"
}

# Extract a field from YAML frontmatter
extract_field() {
  local file="$1" field="$2"
  # Get content between first pair of --- markers, then extract field
  awk '/^---$/{c++; next} c==1{print}' "$file" 2>/dev/null | grep "^${field}:" | head -1 | sed "s/^${field}:[ ]*//"
}

# Generate a bridge wrapper file
generate_wrapper() {
  local cmd_name="$1"
  local plugin_name="$2"
  local source_path="$3"
  
  # Extract metadata from plugin command source
  local description
  description=$(extract_field "$source_path" "description")
  local model
  model=$(extract_field "$source_path" "model")
  
  # Defaults
  [ -z "$description" ] && description="Plugin command from ${plugin_name}"
  [ -z "$model" ] && model="opus"
  
  # Make source relative to BASE_DIR
  local rel_source="${source_path#${BASE_DIR}/}"
  
  cat <<EOF
---
name: ${cmd_name}
description: ${description}
model: ${model}
---
<!-- 🔌 ${BRIDGE_MARKER} | source: ${plugin_name} | DO NOT EDIT -->
<!-- To modify this command, edit: ${rel_source} -->
<!-- Run .logic-loom/scripts/bash/sync-plugin-commands.sh sync to refresh -->

Read and execute the full command procedure from: ${rel_source}
EOF
}

# ── Core Operations ──

# Discover all plugin commands → outputs "cmd_name plugin_name source_path" per line
discover_commands() {
  for plugin_dir in "${PLUGINS_DIR}"/*/; do
    [ -d "$plugin_dir" ] || continue
    local plugin_name
    plugin_name=$(basename "$plugin_dir")
    
    # Skip template plugin
    [ "$plugin_name" = "$TEMPLATE_PLUGIN" ] && continue
    
    local cmds_dir="${plugin_dir}commands"
    [ -d "$cmds_dir" ] || continue
    
    for cmd_file in "${cmds_dir}"/*.md; do
      [ -f "$cmd_file" ] || continue
      local cmd_name
      cmd_name=$(basename "$cmd_file" .md)
      echo "${cmd_name} ${plugin_name} ${cmd_file}"
    done
  done | sort -k1,1
}

# Add missing bridge commands
do_add() {
  local added=0
  local skipped=0
  local conflicts=""
  
  # Track which command names we've seen (first plugin wins)
  local seen_cmds=""
  
  while read -r cmd_name plugin_name source_path; do
    # Check for duplicate command names (conflict)
    if echo "$seen_cmds" | grep -q "^${cmd_name}$"; then
      conflicts="${conflicts}  ⚠️  Conflict: /${cmd_name} also in ${plugin_name} (skipped)\n"
      continue
    fi
    seen_cmds="${seen_cmds}
${cmd_name}"
    
    local target="${COMMANDS_DIR}/${cmd_name}.md"
    
    if [ -f "$target" ]; then
      if is_bridge_command "$target"; then
        # Refresh existing bridge command
        generate_wrapper "$cmd_name" "$plugin_name" "$source_path" > "$target"
        added=$((added + 1))
      else
        # Static command — do not overwrite
        skipped=$((skipped + 1))
      fi
    else
      # New bridge command
      generate_wrapper "$cmd_name" "$plugin_name" "$source_path" > "$target"
      added=$((added + 1))
    fi
  done < <(discover_commands)
  
  if [ -n "$conflicts" ]; then
    echo -e "${YELLOW}${conflicts}${NC}"
  fi
  
  echo -e "${GREEN}✅ Bridge: ${added} commands synced, ${skipped} static commands preserved${NC}"
}

# Remove bridge commands whose plugin source no longer exists
do_prune() {
  local pruned=0
  
  for cmd_file in "${COMMANDS_DIR}"/*.md; do
    [ -f "$cmd_file" ] || continue
    
    if is_bridge_command "$cmd_file"; then
      local cmd_name
      cmd_name=$(basename "$cmd_file" .md)
      
      # Check if any plugin still provides this command
      local found=false
      for plugin_dir in "${PLUGINS_DIR}"/*/; do
        if [ -f "${plugin_dir}commands/${cmd_name}.md" ]; then
          local pname
          pname=$(basename "$plugin_dir")
          [ "$pname" = "$TEMPLATE_PLUGIN" ] && continue
          found=true
          break
        fi
      done
      
      if ! $found; then
        rm "$cmd_file"
        pruned=$((pruned + 1))
        echo -e "${YELLOW}  Pruned: /${cmd_name} (plugin removed)${NC}"
      fi
    fi
  done
  
  echo -e "${GREEN}✅ Pruned: ${pruned} orphaned bridge commands removed${NC}"
}

# Generate manifest file
generate_manifest() {
  local bridged_json=""
  local static_json=""
  local first_bridge=true
  local first_static=true
  
  for cmd_file in "${COMMANDS_DIR}"/*.md; do
    [ -f "$cmd_file" ] || continue
    local cmd_name
    cmd_name=$(basename "$cmd_file" .md)
    
    if is_bridge_command "$cmd_file"; then
      # Extract plugin name from bridge marker comment
      local plugin_name
      plugin_name=$(grep "$BRIDGE_MARKER" "$cmd_file" | sed 's/.*source: //;s/ |.*//')
      
      # Find the source path
      local source_path=""
      for plugin_dir in "${PLUGINS_DIR}"/*/; do
        if [ -f "${plugin_dir}commands/${cmd_name}.md" ]; then
          source_path="${plugin_dir}commands/${cmd_name}.md"
          source_path="${source_path#${BASE_DIR}/}"
          break
        fi
      done
      
      if $first_bridge; then
        first_bridge=false
      else
        bridged_json="${bridged_json},"
      fi
      bridged_json="${bridged_json}
    \"${cmd_name}\": {\"plugin\": \"${plugin_name}\", \"source\": \"${source_path}\"}"
    else
      if $first_static; then
        first_static=false
      else
        static_json="${static_json},"
      fi
      static_json="${static_json} \"${cmd_name}\""
    fi
  done
  
  cat > "$MANIFEST" <<EOF
{
  "generated": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "bridge_marker": "${BRIDGE_MARKER}",
  "bridged": {${bridged_json}
  },
  "static": [${static_json}]
}
EOF
}

# List command → plugin mapping
do_list() {
  echo ""
  echo "Plugin Command Bridge — Mapping"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  printf "  %-20s %-25s %s\n" "COMMAND" "PLUGIN" "TYPE"
  printf "  %-20s %-25s %s\n" "───────" "──────" "────"
  
  for cmd_file in "${COMMANDS_DIR}"/*.md; do
    [ -f "$cmd_file" ] || continue
    local cmd_name
    cmd_name=$(basename "$cmd_file" .md)
    
    if is_bridge_command "$cmd_file"; then
      local plugin_name
      plugin_name=$(grep "$BRIDGE_MARKER" "$cmd_file" | sed 's/.*source: //;s/ |.*//')
      printf "  %-20s %-25s %s\n" "/${cmd_name}" "${plugin_name}" "🔌 bridge"
    else
      printf "  %-20s %-25s %s\n" "/${cmd_name}" "(static)" "📄 static"
    fi
  done | sort
  echo ""
}

# Show status summary
do_status() {
  local bridge_count=0
  local static_count=0
  local plugin_cmd_count=0
  
  for cmd_file in "${COMMANDS_DIR}"/*.md; do
    [ -f "$cmd_file" ] || continue
    if is_bridge_command "$cmd_file"; then
      bridge_count=$((bridge_count + 1))
    else
      static_count=$((static_count + 1))
    fi
  done
  
  # Count total plugin commands
  while read -r _ _ _; do
    plugin_cmd_count=$((plugin_cmd_count + 1))
  done < <(discover_commands)
  
  echo ""
  echo "Plugin Command Bridge — Status"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "  Bridge commands:  ${bridge_count}"
  echo "  Static commands:  ${static_count}"
  echo "  Total .claude/:   $((bridge_count + static_count))"
  echo "  Plugin commands:  ${plugin_cmd_count}"
  echo ""
  
  local coverage_pct=0
  if [ $plugin_cmd_count -gt 0 ]; then
    coverage_pct=$(( (bridge_count + static_count) * 100 / plugin_cmd_count ))
  fi
  echo "  Coverage: ${coverage_pct}% of plugin commands accessible"
  echo ""
}

# ── Main ──

# Ensure commands directory exists
mkdir -p "$COMMANDS_DIR"

case "$ACTION" in
  sync)
    echo -e "${BLUE}🔌 Plugin Command Bridge — Syncing...${NC}"
    do_add
    do_prune
    generate_manifest
    echo -e "${GREEN}✅ Manifest updated: ${MANIFEST}${NC}"
    ;;
  add)
    echo -e "${BLUE}🔌 Plugin Command Bridge — Adding missing...${NC}"
    do_add
    generate_manifest
    ;;
  prune)
    echo -e "${BLUE}🔌 Plugin Command Bridge — Pruning orphans...${NC}"
    do_prune
    generate_manifest
    ;;
  list)
    do_list
    ;;
  status)
    do_status
    ;;
  *)
    echo "Usage: sync-plugin-commands.sh {sync|add|prune|list|status}"
    exit 1
    ;;
esac
