#!/usr/bin/env bash
# UserPromptSubmit Hook: Orchestration Guidance + Memory Context Injection
# Version: 3.0.0 (Feature 005 - Agent Architecture Refactor)
#
# Provides Claude Code with orchestration guidance and memory context via
# additionalContext injection. Does NOT override Claude Code's native capabilities.
#
# Components:
#   1. Domain detection + agent recommendations (sdd-orchestrator-hook plugin)
#   2. Constitutional governance reminder
#   3. Slash command routing (preserved from v2.0)
#   4. Memory context injection (sdd-memory plugin, if available)
#
# Input: JSON via stdin (Claude Code hook contract)
# Output: JSON with hookEventName and additionalContext

set -euo pipefail

# ============================================
# Configuration
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SETTINGS_FILE="$REPO_ROOT/.claude/settings.json"
DOMAINS_CONF="$REPO_ROOT/plugins/sdd-orchestrator-hook/config/domains.conf"
MEMORY_SEARCH="$REPO_ROOT/plugins/sdd-memory/scripts/memory-search.sh"
MEMORY_LOG="$REPO_ROOT/plugins/sdd-memory/scripts/memory-log.sh"
AUDIT_DIR="$REPO_ROOT/.docs/governance/audit"
SESSION_ID="${CLAUDE_SESSION_ID:-$(date +%s)-$$}"
TIMESTAMP=$(date -Iseconds 2>/dev/null || date "+%Y-%m-%dT%H:%M:%S%z")
DATE=$(date "+%Y-%m-%d")

# ============================================
# Functions
# ============================================

# Detect domains from user message using domains.conf
# v2.0: Supports both agent references (value=agent-name) and
#        skill references (value=plugin:skill-name)
detect_domains() {
    local message="$1"
    local domains=""
    local delegates=""

    if [ ! -f "$DOMAINS_CONF" ]; then
        echo ""
        return
    fi

    # Read domain mappings (keyword=delegate format)
    while IFS='=' read -r keyword delegate; do
        # Skip comments and empty lines
        [[ "$keyword" =~ ^[[:space:]]*# ]] && continue
        [[ -z "$keyword" ]] && continue
        keyword=$(echo "$keyword" | xargs)  # trim whitespace
        delegate=$(echo "$delegate" | xargs)

        # Case-insensitive keyword match in message
        if echo "$message" | grep -qi "$keyword"; then
            # Extract domain name from delegate
            local domain
            if echo "$delegate" | grep -q ':'; then
                # Skill-based: sdd-domain-backend:backend-operations -> backend
                domain=$(echo "$delegate" | sed 's/sdd-domain-//' | cut -d: -f1)
            else
                # Legacy agent-based: backend-architect -> backend
                domain=$(echo "$delegate" | sed 's/-specialist//' | sed 's/-architect//' | sed 's/-engineer//' | sed 's/-agent//')
            fi
            if ! echo "$domains" | grep -q "$domain"; then
                domains="${domains:+$domains, }$domain"
                delegates="${delegates:+$delegates, }$delegate"
            fi
        fi
    done < "$DOMAINS_CONF"

    echo "${domains}|${delegates}"
}

# Detect slash command from user input
detect_slash_command() {
    local input="$1"
    local command_name=""
    command_name=$(echo "$input" | grep -oE '<command-name>/[a-z-]+</command-name>' | sed 's/<[^>]*>//g; s|/||' | head -1)
    if [ -n "$command_name" ]; then
        echo "$command_name"
        return
    fi
    command_name=$(echo "$input" | grep -oE '^\s*/[a-z][-a-z]*' | sed 's|^\s*/||' | head -1)
    echo "$command_name"
}

# Generate command-specific routing context
generate_command_context() {
    local command_name="$1"

    local bridge_file="$REPO_ROOT/.claude/commands/${command_name}.md"
    if [ -f "$bridge_file" ] && head -10 "$bridge_file" | grep -q "AUTO-GENERATED by plugin-bridge"; then
        local plugin_source
        plugin_source=$(grep "source:" "$bridge_file" | head -1 | sed 's/.*source: //' | sed 's/ .*//')
        local plugin_cmd="plugins/${plugin_source}/commands/${command_name}.md"

        cat <<CMDEOF

**COMMAND DETECTED**: /${command_name}
**Source**: Plugin bridge -> ${plugin_cmd}
**Action**: Read and execute the full procedure from the plugin command file.
**IMPORTANT**: The plugin command file contains Step-by-step execution instructions including Task tool delegation. Follow them exactly.

CMDEOF
    fi
}

# Generate orchestration guidance
generate_orchestration_guidance() {
    local message="$1"
    local domain_result="$2"
    local command_name="$3"

    local domains delegates delegation
    domains=$(echo "$domain_result" | cut -d'|' -f1)
    delegates=$(echo "$domain_result" | cut -d'|' -f2)

    # Determine delegation strategy
    local domain_count
    domain_count=$(echo "$domains" | tr ',' '\n' | grep -c '[a-z]' 2>/dev/null || echo "0")

    if [ "$domain_count" -eq 0 ]; then
        delegation="direct execution"
    elif [ "$domain_count" -eq 1 ]; then
        # Check if skill-based (contains :) or agent-based
        if echo "$delegates" | grep -q ':'; then
            delegation="delegate to $delegates skill (load Task Brief via extract_skill_brief)"
        else
            delegation="single: $delegates"
        fi
    else
        delegation="team-orchestration (multi-domain: $domains)"
    fi

    cat <<EOF

---

**CONSTITUTIONAL GOVERNANCE REMINDER**

You are operating under the Specification-Driven Development Constitution v3.0.0 with 16 enforceable principles.

**MANDATORY PRE-FLIGHT CHECK (4 Steps):**

1. **CONSTITUTION ACKNOWLEDGMENT**
   - Confirm awareness of all 16 principles (I-XVI)
   - Key principles: II (Test-First), VI (Git Approval), X (Agent Delegation)

2. **DOMAIN ANALYSIS**
   - Scan message for domain keywords
   - Identify: frontend, backend, database, testing, security, performance, etc.

3. **DELEGATION DECISION**
   - 0 domains -> may execute directly
   - 1 domain -> MUST activate specialist skill
   - 2+ domains -> MUST activate team-orchestration skill

4. **EXECUTION AUTHORIZATION**
   - Confirm all steps complete
   - Output compliance summary
   - Proceed with action

**CRITICAL PRINCIPLES:**
- **Principle VI (IMMUTABLE)**: NO autonomous git operations without explicit user approval
- **Principle X (CRITICAL)**: Specialized work -> specialist skills
- **Principle II (IMMUTABLE)**: TDD mandatory, >80% coverage
- **Principle XVI**: Plugin-First Architecture -- all capabilities as plugins

**Compliance Summary Format:**
\`\`\`
Constitutional Compliance Check:
- Domain(s): [none | single: <domain> | multi: <domains>]
- Delegation: [direct execution | <skill-name>]
- Git operations: [none planned | will request approval]
- Proceeding with: [action description]
\`\`\`

EOF

    # Add domain detection results if any domains found
    if [ -n "$domains" ] && [ "$domains" != "" ]; then
        cat <<EOF

**DOMAIN DETECTION** (auto-detected from message):
- Domain(s): $domains
- Recommended delegate(s): $delegates
- Delegation: $delegation

EOF
    fi

    # Add command routing if detected
    if [ -n "$command_name" ]; then
        generate_command_context "$command_name"
    fi
}

# Run memory context search (if sdd-memory plugin installed)
run_memory_search() {
    local message="$1"
    local memory_context=""

    if [ -x "$MEMORY_SEARCH" ]; then
        # Run with 3-second timeout, capture output
        memory_context=$(timeout 3 bash "$MEMORY_SEARCH" "$message" 2>/dev/null || echo "")

        # Log memory search (background, non-blocking)
        if [ -x "$MEMORY_LOG" ] && [ -n "$memory_context" ]; then
            bash "$MEMORY_LOG" "$message" "$memory_context" &
        fi
    fi

    echo "$memory_context"
}

# Create audit log
create_audit_log() {
    local input_summary="$1"
    local command_name="${2:-}"
    local domains="${3:-}"

    mkdir -p "$AUDIT_DIR/$DATE"
    local audit_file="$AUDIT_DIR/$DATE/session-$SESSION_ID.json"

    cat > "$audit_file" <<EOF
{
  "timestamp": "$TIMESTAMP",
  "session_id": "$SESSION_ID",
  "event_type": "orchestration_guidance",
  "layer": "hook",
  "command_detected": "${command_name:-none}",
  "domains_detected": "${domains:-none}",
  "input_summary": "$input_summary",
  "output": {
    "action": "inject_orchestration_guidance",
    "blocked": false
  },
  "constitutional_principles": ["I","II","III","IV","V","VI","VII","VIII","IX","X","XI","XII","XIII","XIV","XV","XVI"],
  "duration_ms": 0
}
EOF
}

# ============================================
# Main Logic
# ============================================

# Graceful error wrapper — NEVER block user requests
main() {
    # Read input from stdin
    local INPUT
    INPUT=$(cat)

    # Extract message content for analysis
    local INPUT_SUMMARY
    INPUT_SUMMARY=$(echo "$INPUT" | head -c 500 | tr -d '\n\r')

    # Detect slash command
    local COMMAND_NAME
    COMMAND_NAME=$(detect_slash_command "$INPUT")

    # Detect domains from message
    local DOMAIN_RESULT
    DOMAIN_RESULT=$(detect_domains "$INPUT_SUMMARY")
    local DOMAINS
    DOMAINS=$(echo "$DOMAIN_RESULT" | cut -d'|' -f1)

    # Create audit log (background, non-blocking)
    create_audit_log "$INPUT_SUMMARY" "$COMMAND_NAME" "$DOMAINS" &

    # Generate orchestration guidance
    local GUIDANCE
    GUIDANCE=$(generate_orchestration_guidance "$INPUT_SUMMARY" "$DOMAIN_RESULT" "$COMMAND_NAME")

    # Run memory context search (if available)
    local MEMORY_CONTEXT
    MEMORY_CONTEXT=$(run_memory_search "$INPUT_SUMMARY")

    # Combine guidance + memory context
    local FULL_CONTEXT="$GUIDANCE"
    if [ -n "$MEMORY_CONTEXT" ]; then
        FULL_CONTEXT="${FULL_CONTEXT}

${MEMORY_CONTEXT}"
    fi

    # Output JSON with hookEventName and additionalContext
    if command -v jq &> /dev/null; then
        local ESCAPED_CONTEXT
        ESCAPED_CONTEXT=$(echo "$FULL_CONTEXT" | jq -Rs '.')
        cat <<EOF
{
  "blocked": false,
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": $ESCAPED_CONTEXT
  }
}
EOF
    else
        local ESCAPED_CONTEXT
        ESCAPED_CONTEXT=$(echo "$FULL_CONTEXT" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g' | tr '\n' ' ')
        cat <<EOF
{
  "blocked": false,
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": "$ESCAPED_CONTEXT"
  }
}
EOF
    fi
}

# Run main with error trap — always return non-blocking JSON on failure
main 2>/dev/null || cat <<'FALLBACK'
{
  "blocked": false,
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": ""
  }
}
FALLBACK

exit 0
