#!/usr/bin/env bash
# UserPromptSubmit Hook: Governance Preflight Check
# Constitutional Principle X enforcement
# Version: 2.0.0
#
# This hook automatically injects constitutional governance context
# on every user message to ensure compliance with all 16 principles.
# Now includes slash command detection for proper routing.
#
# Input: JSON via stdin (Claude Code hook contract)
# Output: JSON with hookEventName and additionalContext

set -euo pipefail

# ============================================
# Configuration
# ============================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../../.." && pwd)"
SETTINGS_FILE="$REPO_ROOT/.claude/settings.json"
AUDIT_DIR="$REPO_ROOT/.docs/governance/audit"
SESSION_ID="${CLAUDE_SESSION_ID:-$(date +%s)-$$}"
TIMESTAMP=$(date -Iseconds 2>/dev/null || date "+%Y-%m-%dT%H:%M:%S%z")
DATE=$(date "+%Y-%m-%d")

# ============================================
# Functions
# ============================================

# Extract agent from settings.json (with or without jq)
get_agent_role() {
    if command -v jq &> /dev/null; then
        jq -r '.agent // "constitutional-governance-agent"' "$SETTINGS_FILE" 2>/dev/null || echo "constitutional-governance-agent"
    else
        grep -o '"agent"[[:space:]]*:[[:space:]]*"[^"]*"' "$SETTINGS_FILE" 2>/dev/null | \
            sed 's/.*"\([^"]*\)".*/\1/' || echo "constitutional-governance-agent"
    fi
}

# Detect slash command from user input
# Returns command name if found, empty string otherwise
detect_slash_command() {
    local input="$1"
    # Extract command name from <command-name> tags (Claude Code hook format)
    local command_name=""
    command_name=$(echo "$input" | grep -oE '<command-name>/[a-z-]+</command-name>' | sed 's/<[^>]*>//g; s|/||' | head -1)
    if [ -n "$command_name" ]; then
        echo "$command_name"
        return
    fi
    # Fallback: detect /command at start of message content
    command_name=$(echo "$input" | grep -oE '^\s*/[a-z][-a-z]*' | sed 's|^\s*/||' | head -1)
    echo "$command_name"
}

# Generate command-specific routing context
generate_command_context() {
    local command_name="$1"
    
    # Check if this command has a plugin source (bridge command)
    local bridge_file="$REPO_ROOT/.claude/commands/${command_name}.md"
    if [ -f "$bridge_file" ] && head -10 "$bridge_file" | grep -q "AUTO-GENERATED by plugin-bridge"; then
        local plugin_source
        plugin_source=$(grep "source:" "$bridge_file" | head -1 | sed 's/.*source: //' | sed 's/ .*//')
        local plugin_cmd="plugins/${plugin_source}/commands/${command_name}.md"
        
        cat <<CMDEOF

**COMMAND DETECTED**: /${command_name}
**Source**: Plugin bridge → ${plugin_cmd}
**Action**: Read and execute the full procedure from the plugin command file.
**IMPORTANT**: The plugin command file contains Step-by-step execution instructions including Task tool delegation. Follow them exactly.

CMDEOF
    fi
}

# Create audit log
create_audit_log() {
    local agent_role="$1"
    local input_summary="$2"
    local command_name="${3:-}"

    mkdir -p "$AUDIT_DIR/$DATE"

    local audit_file="$AUDIT_DIR/$DATE/session-$SESSION_ID.json"

    cat > "$audit_file" <<EOF
{
  "timestamp": "$TIMESTAMP",
  "session_id": "$SESSION_ID",
  "event_type": "context_injection",
  "decision_type": "context_injection",
  "layer": "hook",
  "agent_role": "$agent_role",
  "command_detected": "${command_name:-none}",
  "input_summary": "$input_summary",
  "output": {
    "action": "inject_governance_context",
    "blocked": false
  },
  "constitutional_principles": ["I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI"],
  "duration_ms": 0
}
EOF
}

# Generate governance context message
generate_governance_context() {
    local agent_role="$1"

    cat <<'EOF'

---

**CONSTITUTIONAL GOVERNANCE REMINDER**

You are operating under the Specification-Driven Development Constitution v3.0.0 with 16 enforceable principles.

**MANDATORY PRE-FLIGHT CHECK (4 Steps):**

1. **CONSTITUTION ACKNOWLEDGMENT**
   - Confirm awareness of all 16 principles (I-XVI)
   - Key principles: II (Test-First), VI (Git Approval), X (Agent Delegation)

2. **DOMAIN ANALYSIS**
   - Scan message for domain keywords
   - Identify: frontend, backend, database, testing, security, performance, etc.

3. **DELEGATION DECISION**
   - 0 domains → may execute directly
   - 1 domain → MUST delegate to specialist agent
   - 2+ domains → MUST delegate to task-orchestrator

4. **EXECUTION AUTHORIZATION**
   - Confirm all steps complete
   - Output compliance summary
   - Proceed with action

**CRITICAL PRINCIPLES:**
- **Principle VI (IMMUTABLE)**: NO autonomous git operations without explicit user approval
- **Principle X (CRITICAL)**: Specialized work → specialized agents
- **Principle II (IMMUTABLE)**: TDD mandatory, >80% coverage
- **Principle XVI**: Plugin-First Architecture — all capabilities as plugins

**Compliance Summary Format:**
```
Constitutional Compliance Check:
- Domain(s): [none | single: <domain> | multi: <domains>]
- Delegation: [direct execution | <agent-name>]
- Git operations: [none planned | will request approval]
- Proceeding with: [action description]
```

---
EOF
}

# ============================================
# Main Logic
# ============================================

# Read input from stdin
INPUT=$(cat)

# Extract first 100 chars of user message for audit log
INPUT_SUMMARY=$(echo "$INPUT" | head -c 100 | tr -d '\n\r')

# Detect slash command invocation
COMMAND_NAME=$(detect_slash_command "$INPUT")

# Get agent role from settings
AGENT_ROLE=$(get_agent_role)

# Create audit log (background, non-blocking)
create_audit_log "$AGENT_ROLE" "$INPUT_SUMMARY" "$COMMAND_NAME" &

# Generate governance context
GOVERNANCE_CONTEXT=$(generate_governance_context "$AGENT_ROLE")

# If slash command detected, append command-specific routing
if [ -n "$COMMAND_NAME" ]; then
    COMMAND_CONTEXT=$(generate_command_context "$COMMAND_NAME")
    if [ -n "$COMMAND_CONTEXT" ]; then
        GOVERNANCE_CONTEXT="${GOVERNANCE_CONTEXT}${COMMAND_CONTEXT}"
    fi
fi

# Output JSON with hookEventName and additionalContext (Claude Code hook contract)
if command -v jq &> /dev/null; then
    ESCAPED_CONTEXT=$(echo "$GOVERNANCE_CONTEXT" | jq -Rs '.')
    cat <<EOF
{
  "blocked": false,
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": $ESCAPED_CONTEXT
  }
}
EOF
else
    ESCAPED_CONTEXT=$(echo "$GOVERNANCE_CONTEXT" | sed 's/\\/\\\\/g; s/"/\\"/g; s/\t/\\t/g' | tr '\n' ' ')
    cat <<EOF
{
  "blocked": false,
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": "$ESCAPED_CONTEXT"
  }
}
EOF
fi

exit 0
